# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaInicio.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Busqueda(object):
    def setupUi(self, Busqueda):
        Busqueda.setObjectName("Busqueda")
        Busqueda.resize(700, 700)
        self.centralwidget = QtWidgets.QWidget(Busqueda)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 700, 700))
        self.frame.setStyleSheet("background:rgb(109, 200, 155)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_titulo = QtWidgets.QLabel(self.frame)
        self.label_titulo.setGeometry(QtCore.QRect(6, 1, 691, 41))
        self.label_titulo.setWordWrap(True)
        self.label_titulo.setObjectName("label_titulo")
        self.label_no_informada = QtWidgets.QLabel(self.frame)
        self.label_no_informada.setGeometry(QtCore.QRect(60, 120, 231, 31))
        self.label_no_informada.setObjectName("label_no_informada")
        self.boton_profundidad = QtWidgets.QPushButton(self.frame)
        self.boton_profundidad.setGeometry(QtCore.QRect(120, 180, 121, 51))
        self.boton_profundidad.setStyleSheet("background:rgb(255, 255, 255)")
        self.boton_profundidad.setObjectName("boton_profundidad")
        self.boton_amplitud = QtWidgets.QPushButton(self.frame)
        self.boton_amplitud.setGeometry(QtCore.QRect(120, 260, 121, 51))
        self.boton_amplitud.setStyleSheet("background:rgb(255, 255, 255)")
        self.boton_amplitud.setObjectName("boton_amplitud")
        self.boton_costo = QtWidgets.QPushButton(self.frame)
        self.boton_costo.setGeometry(QtCore.QRect(120, 340, 121, 51))
        self.boton_costo.setStyleSheet("background:rgb(255, 255, 255)")
        self.boton_costo.setObjectName("boton_costo")
        self.boton_avara = QtWidgets.QPushButton(self.frame)
        self.boton_avara.setGeometry(QtCore.QRect(440, 260, 121, 51))
        self.boton_avara.setStyleSheet("background:rgb(255, 255, 255)")
        self.boton_avara.setObjectName("boton_avara")
        self.label_informada = QtWidgets.QLabel(self.frame)
        self.label_informada.setGeometry(QtCore.QRect(380, 120, 231, 31))
        self.label_informada.setObjectName("label_informada")
        self.boton_a = QtWidgets.QPushButton(self.frame)
        self.boton_a.setGeometry(QtCore.QRect(440, 180, 121, 51))
        self.boton_a.setStyleSheet("background:rgb(255, 255, 255)")
        self.boton_a.setObjectName("boton_a")
        Busqueda.setCentralWidget(self.centralwidget)

        self.retranslateUi(Busqueda)
        QtCore.QMetaObject.connectSlotsByName(Busqueda)

    def retranslateUi(self, Busqueda):
        _translate = QtCore.QCoreApplication.translate
        Busqueda.setWindowTitle(_translate("Busqueda", "Busqueda"))
        self.label_titulo.setText(_translate("Busqueda", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">ALGORITMOS DE BUSQUEDA</span></p></body></html>"))
        self.label_no_informada.setText(_translate("Busqueda", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">NO INFORMADA</span></p></body></html>"))
        self.boton_profundidad.setText(_translate("Busqueda", "Profundidad"))
        self.boton_amplitud.setText(_translate("Busqueda", "Amplitud"))
        self.boton_costo.setText(_translate("Busqueda", "Costo"))
        self.boton_avara.setText(_translate("Busqueda", "AVARA"))
        self.label_informada.setText(_translate("Busqueda", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">INFORMADA</span></p></body></html>"))
        self.boton_a.setText(_translate("Busqueda", "A*"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Busqueda = QtWidgets.QMainWindow()
    ui = Ui_Busqueda()
    ui.setupUi(Busqueda)
    Busqueda.show()
    sys.exit(app.exec_())
